### ISSUE TITLE
Missing file in laravel part

### ISSUE THREAD

**Issue by irkreja** [AbdullahValley/bkash#1]
In in description you mentioned bkash.blade.php but in your project there is no such file. Also in Your bkash-script.blade.php there are showLoading is not defined and hideLoading is not defined

**Comment by AbdullahValley** [comment]
Thank You So Much Rejaul Karim Brother. Its a mistake, 
Its bkash-payment.blade.php instead of bkash.blade.php AND showLoading is my custom function for my project. Others user needs to create it by themselves.
